source 'https://rubygems.org'


gem 'rails', '4.2.6'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

gem 'active_model_serializers', '~> 0.10.0.rc2'

gem 'json'

gem 'twilio-ruby'

# gem 'delayed_job'
gem 'delayed_job_active_record'
# gem 'delayed_job_groups_plugin'
# gem 'delayed_job_heartbeat_plugin'
# gem 'delayed_job_worker_pool'



# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
